name: CI + Deploy

on:
  push:
    branches: [ "main" ]   # Trigger on push to main
  pull_request:
    branches: [ "main" ]   # Still run lint on PRs (no deploy here)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Linters
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: lint   # Deploy only if lint passes
    if: github.ref == 'refs/heads/main'  # Deploy only on main branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .   # root folder containing index.html
